### ISSUE TITLE
Is Dr = 3 Dt in 2D?

### ISSUE THREAD

**Issue by yangyushi** [FTurci/active-lammps#1]
Hi Francesco,

I am aways confused by the definition of the diffusion constant.

In [this line](https://github.com/FTurci/active-lammps/blob/7a395b8c7ad63177a258c24c6f28967c8028ebaa/src/fix_abp2d.cpp#L50) of the 2D APB fixer, you wrote something like Dr = 3Dt, but commenting "3D". Does this relationship also hold for 2D?

Best,

Yushi

**Comment by FTurci** [comment]
Hi Yushi,  Dr = 3Dt/sigma^2 is actually valid in 3D. However, I was following the model of Stenhammar et al Soft Matter, 2014, 10, 1489 where they seem to keep the same relationships between Dr and Dt for 2D and 3D (section 2 "Discrete ABP model"). I am not sure that this holds for other implementations of ABPs.
A recent PRL seems to suggest that the same is done in some 2d models (PRL 121, 098003 (2018)), but I think that maybe their friction is wrong (they write D_r = 3 gamma k_B T/sigma^2, but I think that the dimensions are wrong, unless one writes  D_r = 3 k_B T/(gamma sigma^2) , and then Dr= 3Dt/sigma^2).

**Comment by yangyushi** [comment]
Thanks for the reply. I will check on those papers but at this point I am much more confident about the 2D implementation. Cheers!
